#!/usr/bin/env bats
# delivered.sh — the delivery index writer, reader and verifier (plan
# docs/plans/2026-09-07T160328-PLAN--delivery-index.md, F3). RED-FIRST: the
# script under test does not exist yet — every test below is expected to fail
# until F3 lands. That failure IS the point, and this file is committed BEFORE
# it (intra-T1 order: F4 red → F1 → F3 green → F2).
#
# Contract under test (schema doc "The record" + "Hard bans"; write-verify doc §7):
#   Usage: delivered.sh write < record.json
#          delivered.sh read <query> [--layer product|internal] [--limit N] [--no-verify]
#          delivered.sh verify [<id>] [--repair]
#
#   - `set -u` only, NEVER -e: -e would turn a probe result into an exit code,
#     which is qa-preflight.sh's stated reason.
#   - exit 0 for probe results. exit 1 ONLY when the filesystem refuses a write.
#     exit 2 for caller error — a bad mode, bad arguments, a record breaking a
#     hard ban (with REFUSED=<ban>), or an unmet hard dependency (with
#     ERROR=node-missing). The two exit-2 causes MUST be distinguishable by
#     output, which is why they print different keys.
#   - The index is docs/delivered.jsonl, one minified JSON object per line.
#   - `v` and `ts` are generated BY THE SCRIPT, never supplied by the caller
#     (log-jsonl.sh:50 precedent). Hard ban 1 governs lines on disk, not the
#     write input.
#   - THE CORPUS IS `git ls-files --cached --others --exclude-standard`, minus
#     docs/, minus the index. Never a filesystem walk (which reports a deleted
#     thing alive out of a gitignored leftover) and never tracked-only (which
#     reports uncommitted work dead). L1.6 and L1.7 are that pair.
#   - Entry status aggregates from its items: `superseded` (declared) wins;
#     else ALL items gone → gone; else ANY item gone or changed → changed;
#     else live. "ANY gone → entry gone" is explicitly WRONG — an entry with
#     four live items is not absent from the source.
#   - Never rewrites or deletes a line. Corrections are new lines, and the
#     LAST line for an id wins.

setup() {
  load 'test_helper/common-setup'
  common_setup
}

teardown() {
  common_teardown
}

INDEX="docs/delivered.jsonl"

# ─── Fixture helpers ─────────────────────────────────────────────────────────

# src <path> <content...> — write a source file, creating parents.
src() {
  local p=$1; shift
  mkdir -p "$(dirname "$p")"
  printf '%s\n' "$@" > "$p"
}

commit_all() {
  git add -A >/dev/null 2>&1
  git commit -q -m "${1:-fixture}" >/dev/null 2>&1 || true
}

# A record the script must accept. Every test that needs a BROKEN record
# writes its own inline, so the break is visible at the point of use.
valid_record() {
  cat <<'JSON'
{"id":"0042F","layer":"product","by":"done","status":"live","name":"login com Google","words":"login google oauth token social","commits":["a1b2c3d"],"origin":"docs/features/0042F-login-google/","items":[{"what":"POST /auth/google","at":"src/auth/google.ts","find":"authGoogleHandler"}]}
JSON
}

# The source the valid record anchors into.
valid_source() {
  src src/auth/google.ts 'export function authGoogleHandler() { return 1; }'
}

# write_index <line>... — build an index directly, bypassing `write`. Used only
# where the test is about READING, so the fixture may hold states (gone,
# superseded) that `write` would refuse to author from nothing.
write_index() {
  mkdir -p docs
  : > "$INDEX"
  local l
  for l in "$@"; do printf '%s\n' "$l" >> "$INDEX"; done
}

entry() { # entry <id> <status> <name> <words> <at> <find> [extra-json]
  printf '{"v":1,"ts":"2026-09-07T12:00:00Z","id":"%s","layer":"product","by":"done","status":"%s","name":"%s","words":"%s","commits":["a1b2c3d"],"origin":"docs/features/%s/","items":[{"what":"thing","at":"%s","find":"%s"}]%s}' \
    "$1" "$2" "$3" "$4" "$1" "$5" "$6" "${7:-}"
}

# `run` must NEVER sit on the right-hand side of a pipe: bats runs that side in
# a subshell, so $status and $output never reach the assertion and every
# `[ "$status" -eq 0 ]` reads an empty string. Feed the record from a file
# instead, which is also how a real caller invokes it.
run_valid_record_write() {
  valid_record > "$TEST_TEMP_DIR/record.json"
  run bash "$SCRIPTS_DIR/delivered.sh" write < "$TEST_TEMP_DIR/record.json"
}

# Same call when the test only needs the side effect, not the exit status.
write_valid_record() {
  valid_record > "$TEST_TEMP_DIR/record.json"
  bash "$SCRIPTS_DIR/delivered.sh" write < "$TEST_TEMP_DIR/record.json" >/dev/null
}

run_write() { valid_source; commit_all; run_valid_record_write; }

# The ids of the returned entries, in the order the script printed them.
returned_ids() { json_lines | sed -n 's/.*"id":"\([^"]*\)".*/\1/p'; }

index_lines() { wc -l < "$INDEX" | tr -d ' '; }

key() { printf '%s\n' "$output" | grep "^$1=" | head -1 | sed "s/^$1=//"; }

json_lines() { printf '%s\n' "$output" | grep '^{'; }

# A PATH with every dependency the script needs EXCEPT node, built from shims
# so the test is portable instead of guessing where node lives.
node_free_path() {
  local d="$TEST_TEMP_DIR/nonode" b real
  mkdir -p "$d"
  for b in git grep sed awk sort mktemp cat date dirname basename rm mkdir wc head tail tr cut find; do
    real=$(command -v "$b" 2>/dev/null) || continue
    printf '#!/bin/sh\nexec "%s" "$@"\n' "$real" > "$d/$b"
    chmod +x "$d/$b"
  done
  printf '%s' "$d"
}

# ─── L1.1 — write appends one line and reports it ────────────────────────────

@test "L1.1: write accepts a valid record, appends one line, prints ENTRY/CREATED/LINES" {
  run_write
  [ "$status" -eq 0 ]
  [[ "$output" == *"ENTRY=0042F"* ]]
  [[ "$output" == *"CREATED=true"* ]]
  [[ "$output" == *"LINES=1"* ]]
  [ -f "$INDEX" ]
  [ "$(index_lines)" = "1" ]
}

@test "L1.1: the written line is minified — one JSON object, no pretty printing" {
  run_write
  [ "$status" -eq 0 ]
  [ "$(index_lines)" = "1" ]
  run head -1 "$INDEX"
  [[ "$output" == '{'*'}' ]]
  [[ "$output" != *$'\n'* ]]
}

@test "L1.1: the script generates v and ts — the caller supplies neither" {
  run_write
  [ "$status" -eq 0 ]
  run head -1 "$INDEX"
  [[ "$output" == *'"v":1'* ]]
  [[ "$output" =~ \"ts\":\"[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z\" ]]
}

@test "L1.1: a second write reports CREATED=false and LINES=2" {
  run_write
  [ "$status" -eq 0 ]
  run_valid_record_write
  [ "$status" -eq 0 ]
  [[ "$output" == *"CREATED=false"* ]]
  [[ "$output" == *"LINES=2"* ]]
}

@test "L1.1: an existing line is never rewritten — append only" {
  run_write
  local before; before=$(head -1 "$INDEX")
  write_valid_record
  [ "$(head -1 "$INDEX")" = "$before" ]
}

# ─── L1.2 — read: matched fields, ordering, cap ──────────────────────────────

@test "L1.2: read matches on name, words, id, items[].what and items[].find" {
  valid_source; commit_all; write_valid_record

  local q
  for q in "login com Google" "oauth" "0042F" "POST /auth/google" "authGoogleHandler"; do
    run bash "$SCRIPTS_DIR/delivered.sh" read "$q"
    [ "$status" -eq 0 ]
    [[ "$output" == *'"id":"0042F"'* ]] || { echo "query '$q' did not match"; false; }
  done
}

@test "L1.2: the query is case-insensitive — Google finds google" {
  valid_source; commit_all; write_valid_record
  run bash "$SCRIPTS_DIR/delivered.sh" read "GOOGLE"
  [ "$status" -eq 0 ]
  [[ "$output" == *'"id":"0042F"'* ]]
}

@test "L1.2: find stays byte-exact and case-sensitive even though the query is not" {
  # The anchor resolves against a lower-case identifier; an upper-case file
  # must not keep it alive.
  src src/a.ts 'const AUTHGOOGLEHANDLER = 1;'
  commit_all
  run_valid_record_write
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=find-absent"* ]]
}

@test "L1.2: results are pre-sorted live then changed then superseded then gone" {
  src src/live.ts 'const liveThing = 1;'
  src src/chg.ts 'const changedThing = 1;'
  commit_all
  write_index \
    "$(entry 0004F gone     'q gone'       'q gone'       src/gone.ts    goneThing)" \
    "$(entry 0003F superseded 'q superseded' 'q superseded' src/sup.ts   supThing ',\"superseded_by\":\"0009F\"')" \
    "$(entry 0002F changed  'q changed'    'q changed'    src/moved.ts   changedThing)" \
    "$(entry 0001F live     'q live'       'q live'       src/live.ts    liveThing)"

  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify
  [ "$status" -eq 0 ]
  [ "$(returned_ids | tr '\n' ' ')" = "0001F 0002F 0003F 0004F " ]
}

@test "L1.2: dead entries are RETURNED, never filtered" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index \
    "$(entry 0001F live 'q live' 'q live' src/live.ts liveThing)" \
    "$(entry 0004F gone 'q gone' 'q gone' src/gone.ts goneThing)"
  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify
  [ "$status" -eq 0 ]
  [[ "$output" == *'"id":"0004F"'* ]]
  [ "$(json_lines | wc -l | tr -d ' ')" = "2" ]
}

@test "L1.2: read caps at ten by default and the cap is visible in the output" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  mkdir -p docs; : > "$INDEX"
  local i
  for i in $(seq 1 12); do
    entry "00${i}F" live "q entry $i" "q entry" src/live.ts liveThing >> "$INDEX"
    printf '\n' >> "$INDEX"
  done
  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify
  [ "$status" -eq 0 ]
  [ "$(json_lines | wc -l | tr -d ' ')" = "10" ]
  [ "$(key MATCHED)" = "12" ]
  [ "$(key RETURNED)" = "10" ]
  [ "$(key LIMIT)" = "10" ]
}

@test "L1.2: --limit overrides the default cap" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  mkdir -p docs; : > "$INDEX"
  local i
  for i in $(seq 1 5); do entry "00${i}F" live "q entry $i" "q entry" src/live.ts liveThing >> "$INDEX"; printf '\n' >> "$INDEX"; done
  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify --limit 2
  [ "$status" -eq 0 ]
  [ "$(json_lines | wc -l | tr -d ' ')" = "2" ]
  [ "$(key LIMIT)" = "2" ]
}

@test "L1.2: --layer filters" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index \
    "$(entry 0001F live 'q product' 'q product' src/live.ts liveThing)" \
    "$(printf '{"v":1,"ts":"2026-09-07T12:00:00Z","id":"plan-x","layer":"internal","by":"done","status":"live","name":"q internal","words":"q internal","commits":["a1b2c3d"],"origin":"docs/plans/plan-x.md","items":[{"what":"t","at":"src/live.ts","find":"liveThing"}]}')"
  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify --layer product
  [ "$status" -eq 0 ]
  [ "$(json_lines | wc -l | tr -d ' ')" = "1" ]
  [[ "$output" == *'"id":"0001F"'* ]]
}

# ─── L1.3 — last line wins ───────────────────────────────────────────────────

@test "L1.3: two lines for one id — read returns only the later one" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index \
    "$(entry 0001F live 'first name'  'q alpha' src/live.ts liveThing)" \
    "$(entry 0001F live 'second name' 'q alpha' src/live.ts liveThing)"
  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify
  [ "$status" -eq 0 ]
  [ "$(json_lines | wc -l | tr -d ' ')" = "1" ]
  [[ "$output" == *"second name"* ]]
  [[ "$output" != *"first name"* ]]
}

# ─── L1.4 — a corrupt line is skipped and reported, never fatal ──────────────

@test "L1.4: a corrupt line mid-file is skipped, reported by number, others returned" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  mkdir -p docs
  {
    entry 0001F live 'q one' 'q one' src/live.ts liveThing; printf '\n'
    printf '{not json at all\n'
    entry 0003F live 'q three' 'q three' src/live.ts liveThing; printf '\n'
  } > "$INDEX"

  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify
  [ "$status" -eq 0 ]
  [ "$(json_lines | wc -l | tr -d ' ')" = "2" ]
  [ "$(key SKIPPED_LINES)" = "2" ]
}

# ─── L1.5 — verify reports; only --repair writes ─────────────────────────────

@test "L1.5: verify without --repair leaves the file byte-identical" {
  src src/moved.ts 'const changedThing = 1;'
  commit_all
  write_index "$(entry 0002F live 'q' 'q' src/old.ts changedThing)"
  local before; before=$(cksum < "$INDEX")

  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0002F=changed"* ]]
  [[ "$output" == *"REPAIRED=0"* ]]
  [ "$(cksum < "$INDEX")" = "$before" ]
}

@test "L1.5: verify accepts a single id and reports only that entry" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index \
    "$(entry 0001F live 'q one' 'q one' src/live.ts liveThing)" \
    "$(entry 0002F live 'q two' 'q two' src/live.ts liveThing)"
  run bash "$SCRIPTS_DIR/delivered.sh" verify 0001F
  [ "$status" -eq 0 ]
  [[ "$output" == *"0001F="* ]]
  [[ "$output" != *"0002F="* ]]
}

@test "L1.5: a declared superseded entry is never recomputed" {
  # Its source is long gone; status is human-declared and stays.
  commit_all
  write_index "$(entry 0003F superseded 'q' 'q' src/gone.ts supThing ',"superseded_by":"0009F"')"
  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0003F=superseded"* ]]
}

# ─── L1.6 / L1.7 — the corpus rule, in both directions ───────────────────────

@test "L1.6: a stale copy in a gitignored directory does NOT keep an item alive" {
  # THE motivating example. A filesystem walk returns live or changed here.
  src .gitignore 'build/'
  src src/auth/google.ts 'export function authGoogleHandler() { return 1; }'
  commit_all
  write_valid_record

  # Delete the real artefact, leave a leftover copy in the ignored directory.
  rm -f src/auth/google.ts
  src build/google.ts 'export function authGoogleHandler() { return 1; }'
  commit_all

  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0042F=gone"* ]]
}

@test "L1.7: an uncommitted source file is NOT garbage — the anchor resolves live" {
  # A `git ls-files`-only implementation returns gone here.
  commit_all
  src src/auth/google.ts 'export function authGoogleHandler() { return 1; }'
  # deliberately NOT committed
  run_valid_record_write
  [ "$status" -eq 0 ]

  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0042F=live"* ]]
}

# ─── L1.8 — the hard bans, one per run, each with its REFUSED name ───────────

@test "L1.8: an item with no find is refused" {
  valid_source; commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"src/auth/google.ts\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=missing-field"* ]]
}

@test "L1.8: a find containing whitespace is refused" {
  valid_source; commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"src/auth/google.ts\",\"find\":\"POST /auth/google\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=find-whitespace"* ]]
}

@test "L1.8: six items are refused" {
  src src/x.ts 'a1 a2 a3 a4 a5 a6'
  commit_all
  run bash -c 'items=""; for i in 1 2 3 4 5 6; do items="$items,{\"what\":\"w\",\"at\":\"src/x.ts\",\"find\":\"a$i\"}"; done; printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[${items#,}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=too-many-items"* ]]
}

@test "L1.8: zero items are refused" {
  commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=no-items"* ]]
}

@test "L1.8: an item anchored into docs/ is refused" {
  src docs/notes.md 'the docsAnchor lives here'
  commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"docs/notes.md\",\"find\":\"docsAnchor\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=item-in-docs"* ]]
}

@test "L1.8: an item anchored into an ignored path is refused" {
  src .gitignore 'generated/'
  src generated/client.ts 'export const generatedClient = 1;'
  commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"generated/client.ts\",\"find\":\"generatedClient\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=item-ignored"* ]]
}

@test "L1.8: a status outside the four values is refused" {
  valid_source; commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"shipped\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"src/auth/google.ts\",\"find\":\"authGoogleHandler\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=bad-status"* ]]
}

@test "L1.8: superseded without superseded_by is refused" {
  valid_source; commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"superseded\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"src/auth/google.ts\",\"find\":\"authGoogleHandler\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=superseded-without-by"* ]]
}

@test "L1.8: an entry with no commits is refused" {
  valid_source; commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"src/auth/google.ts\",\"find\":\"authGoogleHandler\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=no-commits"* ]]
}

@test "L1.8: a find absent from the corpus is refused (ban 3)" {
  valid_source; commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"src/auth/google.ts\",\"find\":\"neverAppearsAnywhere\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=find-absent"* ]]
}

@test "L1.8: input that is not JSON is refused as caller error" {
  commit_all
  run bash -c 'printf "%s" "not a record" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=invalid-json"* ]]
}

@test "L1.8: a refused write creates no index and appends nothing" {
  valid_source; commit_all
  bash -c 'printf "%s" "not a record" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh" >/dev/null 2>&1
  [ ! -f "$INDEX" ]
}

# ─── L1.9 — the over-match thresholds ────────────────────────────────────────

@test "L1.9: a find matching more than 20 files is refused" {
  local i
  for i in $(seq 1 25); do src "src/f$i.ts" 'const user = 1;'; done
  commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"src/f1.ts\",\"find\":\"user\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=find-over-matched"* ]]
}

@test "L1.9: 1-5 files is accepted silently — no LOOSE flag" {
  local i
  for i in 1 2 3; do src "src/f$i.ts" 'const authGoogleHandler = 1;'; done
  src src/auth/google.ts 'export function authGoogleHandler() { return 1; }'
  commit_all
  run_valid_record_write
  [ "$status" -eq 0 ]
  [[ "$output" != *"LOOSE="* ]]
}

@test "L1.9: 6-20 files is accepted and flagged LOOSE for the preview" {
  local i
  for i in $(seq 1 9); do src "src/f$i.ts" 'const authGoogleHandler = 1;'; done
  src src/auth/google.ts 'export function authGoogleHandler() { return 1; }'
  commit_all
  run_valid_record_write
  [ "$status" -eq 0 ]
  [[ "$output" == *"LOOSE=authGoogleHandler"* ]]
}

# ─── L1.10 / L1.11 — repair only on a unique match ───────────────────────────

@test "L1.10: find absent from at, present in exactly one other file, is changed" {
  src src/moved.ts 'const changedThing = 1;'
  commit_all
  write_index "$(entry 0002F live 'q' 'q' src/old.ts changedThing)"
  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0002F=changed"* ]]
}

@test "L1.10: --repair rewrites at to the unique match, as a NEW line" {
  src src/moved.ts 'const changedThing = 1;'
  commit_all
  write_index "$(entry 0002F live 'q' 'q' src/old.ts changedThing)"

  run bash "$SCRIPTS_DIR/delivered.sh" verify --repair
  [ "$status" -eq 0 ]
  [[ "$output" == *"REPAIRED=1"* ]]
  [ "$(index_lines)" = "2" ]
  # the original line survives untouched — corrections are new lines
  [[ "$(head -1 "$INDEX")" == *'"at":"src/old.ts"'* ]]
  [[ "$(tail -1 "$INDEX")" == *'"at":"src/moved.ts"'* ]]
  [[ "$(tail -1 "$INDEX")" == *'"by":"verify"'* ]]
  [[ "$(tail -1 "$INDEX")" == *'"status":"changed"'* ]]
}

@test "L1.11: three other matches means changed with at UNCHANGED even under --repair" {
  src src/a.ts 'const changedThing = 1;'
  src src/b.ts 'const changedThing = 2;'
  src src/c.ts 'const changedThing = 3;'
  commit_all
  write_index "$(entry 0002F live 'q' 'q' src/old.ts changedThing)"

  run bash "$SCRIPTS_DIR/delivered.sh" verify --repair
  [ "$status" -eq 0 ]
  [[ "$output" == *"0002F=changed"* ]]
  [[ "$output" == *"REPAIRED=0"* ]]
  [ "$(index_lines)" = "1" ]
}

@test "L1.11: repair is idempotent — a second run finds nothing to repair" {
  src src/moved.ts 'const changedThing = 1;'
  commit_all
  write_index "$(entry 0002F live 'q' 'q' src/old.ts changedThing)"
  bash "$SCRIPTS_DIR/delivered.sh" verify --repair >/dev/null
  run bash "$SCRIPTS_DIR/delivered.sh" verify --repair
  [ "$status" -eq 0 ]
  [[ "$output" == *"REPAIRED=0"* ]]
  [ "$(index_lines)" = "2" ]
}

# ─── Status aggregation — the rule the design left open ──────────────────────

@test "aggregation: ALL items gone makes the entry gone" {
  commit_all
  write_index "$(printf '{"v":1,"ts":"2026-09-07T12:00:00Z","id":"0005F","layer":"product","by":"done","status":"live","name":"q","words":"q","commits":["a1b2c3d"],"origin":"o","items":[{"what":"a","at":"src/x.ts","find":"aaaGone"},{"what":"b","at":"src/y.ts","find":"bbbGone"}]}')"
  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0005F=gone"* ]]
}

@test "aggregation: ONE gone among live items makes the entry changed, NEVER gone" {
  # The wrong rule ("any gone -> gone") buries a mostly-alive feature.
  src src/x.ts 'const aaaLive = 1;'
  commit_all
  write_index "$(printf '{"v":1,"ts":"2026-09-07T12:00:00Z","id":"0006F","layer":"product","by":"done","status":"live","name":"q","words":"q","commits":["a1b2c3d"],"origin":"o","items":[{"what":"a","at":"src/x.ts","find":"aaaLive"},{"what":"b","at":"src/y.ts","find":"bbbGone"}]}')"
  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0006F=changed"* ]]
}

@test "aggregation: every item resolving at its own at makes the entry live" {
  src src/x.ts 'const aaaLive = 1;'
  src src/y.ts 'const bbbLive = 2;'
  commit_all
  write_index "$(printf '{"v":1,"ts":"2026-09-07T12:00:00Z","id":"0007F","layer":"product","by":"done","status":"live","name":"q","words":"q","commits":["a1b2c3d"],"origin":"o","items":[{"what":"a","at":"src/x.ts","find":"aaaLive"},{"what":"b","at":"src/y.ts","find":"bbbLive"}]}')"
  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0007F=live"* ]]
}

# ─── L1.12 — --no-verify opens no source file ────────────────────────────────

@test "L1.12: --no-verify returns the stored status and opens no source file" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index "$(entry 0001F live 'q' 'q' src/live.ts liveThing)"
  # Remove the source. A verifying read would say gone; --no-verify must not look.
  rm -f src/live.ts
  commit_all

  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify
  [ "$status" -eq 0 ]
  [[ "$output" == *'"status":"live"'* ]]
}

@test "L1.12: the same read WITHOUT --no-verify reports the truth" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index "$(entry 0001F live 'q' 'q' src/live.ts liveThing)"
  rm -f src/live.ts
  commit_all

  run bash "$SCRIPTS_DIR/delivered.sh" read "q"
  [ "$status" -eq 0 ]
  [[ "$output" == *'"status":"gone"'* ]]
}

@test "L1.12: a verifying read never writes — the file stays byte-identical" {
  src src/moved.ts 'const changedThing = 1;'
  commit_all
  write_index "$(entry 0002F live 'q' 'q' src/old.ts changedThing)"
  local before; before=$(cksum < "$INDEX")
  bash "$SCRIPTS_DIR/delivered.sh" read "q" >/dev/null
  [ "$(cksum < "$INDEX")" = "$before" ]
}

# ─── L1.13 — misuse and a refused write ──────────────────────────────────────

@test "L1.13: a bad mode exits 2" {
  run bash "$SCRIPTS_DIR/delivered.sh" frobnicate
  [ "$status" -eq 2 ]
}

@test "L1.13: no arguments exits 2" {
  run bash "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
}

@test "L1.13: read without a query exits 2" {
  run bash "$SCRIPTS_DIR/delivered.sh" read
  [ "$status" -eq 2 ]
}

@test "L1.13: an unknown flag exits 2" {
  commit_all
  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --sort-by-vibes
  [ "$status" -eq 2 ]
}

@test "L1.13: a write the filesystem refuses exits 1, never 0" {
  valid_source; commit_all
  # `docs` is a regular file, so the index directory cannot be created.
  rm -rf docs
  printf 'not a directory\n' > docs
  run_valid_record_write
  [ "$status" -eq 1 ]
  [[ "$output" != *"ENTRY="* ]]
}

@test "L1.13: a missing node prints ERROR=node-missing and exits 2, distinct from REFUSED" {
  commit_all
  local p; p=$(node_free_path)
  PATH="$p" run bash "$SCRIPTS_DIR/delivered.sh" read "q"
  [ "$status" -eq 2 ]
  [[ "$output" == *"ERROR=node-missing"* ]]
  [[ "$output" != *"REFUSED="* ]]
}

# ─── Absence is a no-op, never an error ──────────────────────────────────────

@test "an absent index makes read a no-op with a note, exit 0" {
  commit_all
  run bash "$SCRIPTS_DIR/delivered.sh" read "anything"
  [ "$status" -eq 0 ]
  [ "$(key MATCHED)" = "0" ]
  [ ! -f "$INDEX" ]
}

@test "an absent index makes verify a no-op, exit 0, and scaffolds nothing" {
  commit_all
  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"REPAIRED=0"* ]]
  [ ! -f "$INDEX" ]
}
