#!/usr/bin/env bats
# delivered.sh — the delivery index writer, reader and verifier (plan
# docs/plans/2026-09-07T160328-PLAN--delivery-index.md, F3). RED-FIRST: the
# script under test does not exist yet — every test below is expected to fail
# until F3 lands. That failure IS the point, and this file is committed BEFORE
# it (intra-T1 order: F4 red → F1 → F3 green → F2).
#
# Contract under test (schema doc "The record" + "Hard bans"; write-verify doc §7):
#   Usage: delivered.sh write < record.json
#          delivered.sh read <query> [--layer product|internal] [--limit N] [--no-verify]
#          delivered.sh verify [<id>] [--repair]
#
#   - `set -u` only, NEVER -e: -e would turn a probe result into an exit code,
#     which is qa-preflight.sh's stated reason.
#   - exit 0 for probe results. exit 1 ONLY when the filesystem refuses a write.
#     exit 2 for caller error — a bad mode, bad arguments, a record breaking a
#     hard ban (with REFUSED=<ban>), or an unmet hard dependency (with
#     ERROR=node-missing). The two exit-2 causes MUST be distinguishable by
#     output, which is why they print different keys.
#   - The index is docs/delivered.jsonl, one minified JSON object per line.
#   - `v` and `ts` are generated BY THE SCRIPT, never supplied by the caller
#     (log-jsonl.sh:50 precedent). Hard ban 1 governs lines on disk, not the
#     write input.
#   - THE CORPUS IS `git ls-files --cached --others --exclude-standard`, minus
#     docs/, minus the index. Never a filesystem walk (which reports a deleted
#     thing alive out of a gitignored leftover) and never tracked-only (which
#     reports uncommitted work dead). L1.6 and L1.7 are that pair.
#   - Entry status aggregates from its items: `superseded` (declared) wins;
#     else ALL items gone → gone; else ANY item gone or changed → changed;
#     else live. "ANY gone → entry gone" is explicitly WRONG — an entry with
#     four live items is not absent from the source.
#   - `touched <path>...` answers which deliveries changed those paths, in two
#     labelled layers: `complete` from the delivery's own commit, `curated`
#     from its `items[].at` anchors.
#   - Never rewrites or deletes a line. Corrections are new lines, and the
#     LAST line for an id wins.

setup() {
  load 'test_helper/common-setup'
  common_setup
}

teardown() {
  common_teardown
}

INDEX="docs/delivered.jsonl"

# ─── Fixture helpers ─────────────────────────────────────────────────────────

# src <path> <content...> — write a source file, creating parents.
src() {
  local p=$1; shift
  mkdir -p "$(dirname "$p")"
  printf '%s\n' "$@" > "$p"
}

commit_all() {
  git add -A >/dev/null 2>&1
  git commit -q -m "${1:-fixture}" >/dev/null 2>&1 || true
}

# A record the script must accept. Every test that needs a BROKEN record
# writes its own inline, so the break is visible at the point of use.
valid_record() {
  cat <<'JSON'
{"id":"0042F","layer":"product","by":"done","status":"live","name":"login com Google","words":"login google oauth token social","commits":["a1b2c3d"],"origin":"docs/features/0042F-login-google/","items":[{"what":"POST /auth/google","at":"src/auth/google.ts","find":"authGoogleHandler"}]}
JSON
}

# The source the valid record anchors into.
valid_source() {
  src src/auth/google.ts 'export function authGoogleHandler() { return 1; }'
}

# write_index <line>... — build an index directly, bypassing `write`. Used only
# where the test is about READING, so the fixture may hold states (gone,
# superseded) that `write` would refuse to author from nothing.
write_index() {
  mkdir -p docs
  : > "$INDEX"
  local l
  for l in "$@"; do printf '%s\n' "$l" >> "$INDEX"; done
}

entry() { # entry <id> <status> <name> <words> <at> <find> [extra-json]
  printf '{"v":1,"ts":"2026-09-07T12:00:00Z","id":"%s","layer":"product","by":"done","status":"%s","name":"%s","words":"%s","commits":["a1b2c3d"],"origin":"docs/features/%s/","items":[{"what":"thing","at":"%s","find":"%s"}]%s}' \
    "$1" "$2" "$3" "$4" "$1" "$5" "$6" "${7:-}"
}

# `run` must NEVER sit on the right-hand side of a pipe: bats runs that side in
# a subshell, so $status and $output never reach the assertion and every
# `[ "$status" -eq 0 ]` reads an empty string. Feed the record from a file
# instead, which is also how a real caller invokes it.
run_valid_record_write() {
  valid_record > "$TEST_TEMP_DIR/record.json"
  run bash "$SCRIPTS_DIR/delivered.sh" write < "$TEST_TEMP_DIR/record.json"
}

# Same call when the test only needs the side effect, not the exit status.
write_valid_record() {
  valid_record > "$TEST_TEMP_DIR/record.json"
  bash "$SCRIPTS_DIR/delivered.sh" write < "$TEST_TEMP_DIR/record.json" >/dev/null
}

run_write() { valid_source; commit_all; run_valid_record_write; }

# The ids of the returned entries, in the order the script printed them.
returned_ids() { json_lines | sed -n 's/.*"id":"\([^"]*\)".*/\1/p'; }

index_lines() { wc -l < "$INDEX" | tr -d ' '; }

key() { printf '%s\n' "$output" | grep "^$1=" | head -1 | sed "s/^$1=//"; }

json_lines() { printf '%s\n' "$output" | grep '^{'; }

# A PATH with every dependency the script needs EXCEPT node, built from shims
# so the test is portable instead of guessing where node lives.
node_free_path() {
  local d="$TEST_TEMP_DIR/nonode" b real
  mkdir -p "$d"
  # `bash` and `sh` are in the list because `run bash <script>` resolves the
  # interpreter through this PATH too — without them the test would report 127
  # (command not found) instead of the 2 it is asserting.
  for b in bash sh env git grep sed awk sort mktemp cat date dirname basename rm mkdir wc head tail tr cut find; do
    real=$(command -v "$b" 2>/dev/null) || continue
    printf '#!/bin/sh\nexec "%s" "$@"\n' "$real" > "$d/$b"
    chmod +x "$d/$b"
  done
  printf '%s' "$d"
}

# ─── L1.1 — write appends one line and reports it ────────────────────────────

@test "L1.1: write accepts a valid record, appends one line, prints ENTRY/CREATED/LINES" {
  run_write
  [ "$status" -eq 0 ]
  [[ "$output" == *"ENTRY=0042F"* ]]
  [[ "$output" == *"CREATED=true"* ]]
  [[ "$output" == *"LINES=1"* ]]
  [ -f "$INDEX" ]
  [ "$(index_lines)" = "1" ]
}

@test "L1.1: the written line is minified — one JSON object, no pretty printing" {
  run_write
  [ "$status" -eq 0 ]
  [ "$(index_lines)" = "1" ]
  run head -1 "$INDEX"
  [[ "$output" == '{'*'}' ]]
  [[ "$output" != *$'\n'* ]]
}

@test "L1.1: the script generates v and ts — the caller supplies neither" {
  run_write
  [ "$status" -eq 0 ]
  run head -1 "$INDEX"
  [[ "$output" == *'"v":1'* ]]
  [[ "$output" =~ \"ts\":\"[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z\" ]]
}

@test "L1.1: a second write reports CREATED=false and LINES=2" {
  run_write
  [ "$status" -eq 0 ]
  run_valid_record_write
  [ "$status" -eq 0 ]
  [[ "$output" == *"CREATED=false"* ]]
  [[ "$output" == *"LINES=2"* ]]
}

@test "L1.1: an existing line is never rewritten — append only" {
  run_write
  local before; before=$(head -1 "$INDEX")
  write_valid_record
  [ "$(head -1 "$INDEX")" = "$before" ]
}

# ─── L1.2 — read: matched fields, ordering, cap ──────────────────────────────

@test "L1.2: read matches on name, words, id, items[].what and items[].find" {
  valid_source; commit_all; write_valid_record

  local q
  for q in "login com Google" "oauth" "0042F" "POST /auth/google" "authGoogleHandler"; do
    run bash "$SCRIPTS_DIR/delivered.sh" read "$q"
    [ "$status" -eq 0 ]
    [[ "$output" == *'"id":"0042F"'* ]] || { echo "query '$q' did not match"; false; }
  done
}

@test "L1.2: the query is case-insensitive — Google finds google" {
  valid_source; commit_all; write_valid_record
  run bash "$SCRIPTS_DIR/delivered.sh" read "GOOGLE"
  [ "$status" -eq 0 ]
  [[ "$output" == *'"id":"0042F"'* ]]
}

@test "L1.2: find stays byte-exact and case-sensitive even though the query is not" {
  # The anchor resolves against a lower-case identifier; an upper-case file
  # must not keep it alive.
  src src/a.ts 'const AUTHGOOGLEHANDLER = 1;'
  commit_all
  run_valid_record_write
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=find-absent"* ]]
}

@test "L1.2: two terms in the opposite order still match" {
  # The haystack joins id, name, words, node, what[] and find[] with spaces, so
  # the fixture keeps the two terms apart in the JOINED string, not merely in
  # different fields — adjacent fields would make them contiguous by accident.
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index "$(entry 0001F live 'alpha beta omega' 'zzz' src/live.ts liveThing)"
  run bash "$SCRIPTS_DIR/delivered.sh" read "omega alpha" --no-verify
  [ "$status" -eq 0 ]
  [[ "$output" == *'"id":"0001F"'* ]]
}

@test "L1.2: two terms drawn from different fields match" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index "$(entry 0001F live 'alpha' 'zzz omega' src/live.ts liveThing)"
  run bash "$SCRIPTS_DIR/delivered.sh" read "alpha omega" --no-verify
  [ "$status" -eq 0 ]
  [[ "$output" == *'"id":"0001F"'* ]]
}

@test "L1.2: an entry hitting every term outranks one hitting a single term" {
  # Same status and same ts, so without a score the tie breaks on id and 0001F
  # would lead. With one, the three-hit entry leads despite its id sorting last.
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index     "$(entry 0001F live 'alpha' 'zzz' src/live.ts liveThing)"     "$(entry 0009F live 'alpha' 'zzz beta yyy gamma' src/live.ts liveThing)"
  run bash "$SCRIPTS_DIR/delivered.sh" read "alpha beta gamma" --no-verify
  [ "$status" -eq 0 ]
  [ "$(returned_ids | head -1)" = "0009F" ]
}

@test "L1.2: an entry matching no term at all is absent from both buckets" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index "$(entry 0001F live 'alpha' 'zzz' src/live.ts liveThing)"
  run bash "$SCRIPTS_DIR/delivered.sh" read "qqqq wwww" --no-verify
  [ "$status" -eq 0 ]
  [ "$(key MATCHED_LIVE)" = "0" ]
  [ "$(key MATCHED_DEAD)" = "0" ]
  [ "$(json_lines | wc -l | tr -d ' ')" = "0" ]
}

@test "L1.2: items[].at stays out of the haystack even under per-term matching" {
  # --repair rewrites `at` on every anchor move, so a query must never hit it.
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index "$(entry 0001F live 'alpha' 'zzz' src/uniquepathmarker.ts liveThing)"
  run bash "$SCRIPTS_DIR/delivered.sh" read "uniquepathmarker" --no-verify
  [ "$status" -eq 0 ]
  [ "$(key MATCHED_LIVE)" = "0" ]
  [ "$(key MATCHED_DEAD)" = "0" ]
}

@test "L1.2: results are pre-sorted live then changed then superseded then gone" {
  src src/live.ts 'const liveThing = 1;'
  src src/chg.ts 'const changedThing = 1;'
  commit_all
  write_index \
    "$(entry 0004F gone     'q gone'       'q gone'       src/gone.ts    goneThing)" \
    "$(entry 0003F superseded 'q superseded' 'q superseded' src/sup.ts   supThing ',"superseded_by":"0009F"')" \
    "$(entry 0002F changed  'q changed'    'q changed'    src/moved.ts   changedThing)" \
    "$(entry 0001F live     'q live'       'q live'       src/live.ts    liveThing)"

  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify
  [ "$status" -eq 0 ]
  [ "$(returned_ids | tr '\n' ' ')" = "0001F 0002F 0003F 0004F " ]
}

@test "L1.2: dead entries get their own reserved slots, not the leftovers of one cut" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index \
    "$(entry 0001F live 'q live' 'q live' src/live.ts liveThing)" \
    "$(entry 0004F gone 'q gone' 'q gone' src/gone.ts goneThing)"
  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify
  [ "$status" -eq 0 ]
  [[ "$output" == *'"id":"0004F"'* ]]
  [ "$(json_lines | wc -l | tr -d ' ')" = "2" ]
  [ "$(key MATCHED_LIVE)" = "1" ]
  [ "$(key MATCHED_DEAD)" = "1" ]
  [ "$(key RETURNED_DEAD)" = "1" ]
}

@test "L1.2: the read returns five live and two dead, and counts each bucket" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  mkdir -p docs; : > "$INDEX"
  local i
  for i in $(seq 1 12); do
    entry "L${i}" live "q entry $i" "q entry" src/live.ts liveThing >> "$INDEX"
    printf '\n' >> "$INDEX"
  done
  for i in $(seq 1 3); do
    entry "D${i}" gone "q dead $i" "q dead" src/gone.ts goneThing >> "$INDEX"
    printf '\n' >> "$INDEX"
  done
  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify
  [ "$status" -eq 0 ]
  [ "$(key MATCHED_LIVE)" = "12" ]
  [ "$(key MATCHED_DEAD)" = "3" ]
  [ "$(key RETURNED_LIVE)" = "5" ]
  [ "$(key RETURNED_DEAD)" = "2" ]
  [ "$(json_lines | wc -l | tr -d ' ')" = "7" ]
}

@test "L1.2: --limit sets the live cap and leaves the dead cap alone" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  mkdir -p docs; : > "$INDEX"
  local i
  for i in $(seq 1 12); do
    entry "L${i}" live "q entry $i" "q entry" src/live.ts liveThing >> "$INDEX"
    printf '\n' >> "$INDEX"
  done
  for i in $(seq 1 3); do
    entry "D${i}" gone "q dead $i" "q dead" src/gone.ts goneThing >> "$INDEX"
    printf '\n' >> "$INDEX"
  done
  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify --limit 1
  [ "$status" -eq 0 ]
  [ "$(key RETURNED_LIVE)" = "1" ]
  [ "$(key RETURNED_DEAD)" = "2" ]
  [ "$(json_lines | wc -l | tr -d ' ')" = "3" ]
}

@test "L1.2: unused dead slots are never backfilled with live entries" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  mkdir -p docs; : > "$INDEX"
  local i
  for i in $(seq 1 12); do
    entry "L${i}" live "q entry $i" "q entry" src/live.ts liveThing >> "$INDEX"
    printf '\n' >> "$INDEX"
  done
  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify
  [ "$status" -eq 0 ]
  [ "$(key RETURNED_LIVE)" = "5" ]
  [ "$(key RETURNED_DEAD)" = "0" ]
  [ "$(json_lines | wc -l | tr -d ' ')" = "5" ]
}

@test "L1.2: --layer filters" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index \
    "$(entry 0001F live 'q product' 'q product' src/live.ts liveThing)" \
    "$(printf '{"v":1,"ts":"2026-09-07T12:00:00Z","id":"plan-x","layer":"internal","by":"done","status":"live","name":"q internal","words":"q internal","commits":["a1b2c3d"],"origin":"docs/plans/plan-x.md","items":[{"what":"t","at":"src/live.ts","find":"liveThing"}]}')"
  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify --layer product
  [ "$status" -eq 0 ]
  [ "$(json_lines | wc -l | tr -d ' ')" = "1" ]
  [[ "$output" == *'"id":"0001F"'* ]]
}

# ─── L1.3 — last line wins ───────────────────────────────────────────────────

@test "L1.3: two lines for one id — read returns only the later one" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index \
    "$(entry 0001F live 'first name'  'q alpha' src/live.ts liveThing)" \
    "$(entry 0001F live 'second name' 'q alpha' src/live.ts liveThing)"
  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify
  [ "$status" -eq 0 ]
  [ "$(json_lines | wc -l | tr -d ' ')" = "1" ]
  [[ "$output" == *"second name"* ]]
  [[ "$output" != *"first name"* ]]
}

# ─── L1.4 — a corrupt line is skipped and reported, never fatal ──────────────

@test "L1.4: a corrupt line mid-file is skipped, reported by number, others returned" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  mkdir -p docs
  {
    entry 0001F live 'q one' 'q one' src/live.ts liveThing; printf '\n'
    printf '{not json at all\n'
    entry 0003F live 'q three' 'q three' src/live.ts liveThing; printf '\n'
  } > "$INDEX"

  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify
  [ "$status" -eq 0 ]
  [ "$(json_lines | wc -l | tr -d ' ')" = "2" ]
  [ "$(key SKIPPED_LINES)" = "2" ]
}

# ─── L1.5 — verify reports; only --repair writes ─────────────────────────────

@test "L1.5: verify without --repair leaves the file byte-identical" {
  src src/moved.ts 'const changedThing = 1;'
  commit_all
  write_index "$(entry 0002F live 'q' 'q' src/old.ts changedThing)"
  local before; before=$(cksum < "$INDEX")

  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0002F=changed"* ]]
  [[ "$output" == *"REPAIRED=0"* ]]
  [ "$(cksum < "$INDEX")" = "$before" ]
}

@test "L1.5: verify accepts a single id and reports only that entry" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index \
    "$(entry 0001F live 'q one' 'q one' src/live.ts liveThing)" \
    "$(entry 0002F live 'q two' 'q two' src/live.ts liveThing)"
  run bash "$SCRIPTS_DIR/delivered.sh" verify 0001F
  [ "$status" -eq 0 ]
  [[ "$output" == *"0001F="* ]]
  [[ "$output" != *"0002F="* ]]
}

@test "L1.5: a declared superseded entry is never recomputed" {
  # Its source is long gone; status is human-declared and stays.
  commit_all
  write_index "$(entry 0003F superseded 'q' 'q' src/gone.ts supThing ',"superseded_by":"0009F"')"
  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0003F=superseded"* ]]
}

# ─── L1.6 / L1.7 — the corpus rule, in both directions ───────────────────────

@test "L1.6: a stale copy in a gitignored directory does NOT keep an item alive" {
  # THE motivating example. A filesystem walk returns live or changed here.
  src .gitignore 'build/'
  src src/auth/google.ts 'export function authGoogleHandler() { return 1; }'
  commit_all
  write_valid_record

  # Delete the real artefact, leave a leftover copy in the ignored directory.
  rm -f src/auth/google.ts
  src build/google.ts 'export function authGoogleHandler() { return 1; }'
  commit_all

  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0042F=gone"* ]]
}

@test "L1.7: an uncommitted source file is NOT garbage — the anchor resolves live" {
  # A `git ls-files`-only implementation returns gone here.
  commit_all
  src src/auth/google.ts 'export function authGoogleHandler() { return 1; }'
  # deliberately NOT committed
  run_valid_record_write
  [ "$status" -eq 0 ]

  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0042F=live"* ]]
}

# ─── L1.8 — the hard bans, one per run, each with its REFUSED name ───────────

@test "L1.8: an item with no find is refused" {
  valid_source; commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"src/auth/google.ts\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=missing-field"* ]]
}

@test "L1.8: a find containing whitespace is refused" {
  valid_source; commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"src/auth/google.ts\",\"find\":\"POST /auth/google\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=find-whitespace"* ]]
}

@test "L1.8: six items are accepted — there is no ceiling" {
  src src/x.ts 'a1 a2 a3 a4 a5 a6'
  commit_all
  run bash -c 'items=""; for i in 1 2 3 4 5 6; do items="$items,{\"what\":\"w\",\"at\":\"src/x.ts\",\"find\":\"a$i\"}"; done; printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[${items#,}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 0 ]
  [[ "$output" == *"ENTRY=0042F"* ]]
}

@test "L1.8: zero items are refused" {
  commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=no-items"* ]]
}

@test "L1.8: an item anchored into docs/ is refused" {
  src docs/notes.md 'the docsAnchor lives here'
  commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"docs/notes.md\",\"find\":\"docsAnchor\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=item-in-docs"* ]]
}

@test "L1.8: an item anchored into an ignored path is refused" {
  src .gitignore 'generated/'
  src generated/client.ts 'export const generatedClient = 1;'
  commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"generated/client.ts\",\"find\":\"generatedClient\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=item-ignored"* ]]
}

@test "L1.8: a status outside the four values is refused" {
  valid_source; commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"shipped\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"src/auth/google.ts\",\"find\":\"authGoogleHandler\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=bad-status"* ]]
}

@test "L1.8: superseded without superseded_by is refused" {
  valid_source; commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"superseded\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"src/auth/google.ts\",\"find\":\"authGoogleHandler\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=superseded-without-by"* ]]
}

@test "L1.8: an entry with no commits is refused" {
  valid_source; commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"src/auth/google.ts\",\"find\":\"authGoogleHandler\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=no-commits"* ]]
}

@test "L1.8: a find absent from the corpus is refused (ban 3)" {
  valid_source; commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"src/auth/google.ts\",\"find\":\"neverAppearsAnywhere\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=find-absent"* ]]
}

@test "L1.8: input that is not JSON is refused as caller error" {
  commit_all
  run bash -c 'printf "%s" "not a record" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=invalid-json"* ]]
}

@test "L1.8: a refused write creates no index and appends nothing" {
  valid_source; commit_all
  bash -c 'printf "%s" "not a record" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh" >/dev/null 2>&1 || true
  [ ! -f "$INDEX" ]
}

# ─── L1.9 — the over-match thresholds ────────────────────────────────────────

@test "L1.9: a find matching more than 20 files is refused" {
  local i
  for i in $(seq 1 25); do src "src/f$i.ts" 'const user = 1;'; done
  commit_all
  run bash -c 'printf "%s" "{\"id\":\"0042F\",\"layer\":\"product\",\"by\":\"done\",\"status\":\"live\",\"name\":\"n\",\"words\":\"w\",\"commits\":[\"a1b2c3d\"],\"origin\":\"o\",\"items\":[{\"what\":\"w\",\"at\":\"src/f1.ts\",\"find\":\"user\"}]}" | bash "$0" write' "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
  [[ "$output" == *"REFUSED=find-over-matched"* ]]
}

@test "L1.9: 1-5 files is accepted silently — no LOOSE flag" {
  local i
  for i in 1 2 3; do src "src/f$i.ts" 'const authGoogleHandler = 1;'; done
  src src/auth/google.ts 'export function authGoogleHandler() { return 1; }'
  commit_all
  run_valid_record_write
  [ "$status" -eq 0 ]
  [[ "$output" != *"LOOSE="* ]]
}

@test "L1.9: 6-20 files is accepted and flagged LOOSE for the preview" {
  local i
  for i in $(seq 1 9); do src "src/f$i.ts" 'const authGoogleHandler = 1;'; done
  src src/auth/google.ts 'export function authGoogleHandler() { return 1; }'
  commit_all
  run_valid_record_write
  [ "$status" -eq 0 ]
  [[ "$output" == *"LOOSE=authGoogleHandler"* ]]
}

# ─── L1.10 / L1.11 — repair only on a unique match ───────────────────────────

@test "L1.10: find absent from at, present in exactly one other file, is changed" {
  src src/moved.ts 'const changedThing = 1;'
  commit_all
  write_index "$(entry 0002F live 'q' 'q' src/old.ts changedThing)"
  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0002F=changed"* ]]
}

@test "L1.10: --repair rewrites at to the unique match, as a NEW line" {
  src src/moved.ts 'const changedThing = 1;'
  commit_all
  write_index "$(entry 0002F live 'q' 'q' src/old.ts changedThing)"

  run bash "$SCRIPTS_DIR/delivered.sh" verify --repair
  [ "$status" -eq 0 ]
  [[ "$output" == *"REPAIRED=1"* ]]
  [ "$(index_lines)" = "2" ]
  # the original line survives untouched — corrections are new lines
  [[ "$(head -1 "$INDEX")" == *'"at":"src/old.ts"'* ]]
  [[ "$(tail -1 "$INDEX")" == *'"at":"src/moved.ts"'* ]]
  [[ "$(tail -1 "$INDEX")" == *'"by":"verify"'* ]]
  [[ "$(tail -1 "$INDEX")" == *'"status":"changed"'* ]]
}

@test "L1.11: three other matches means changed with at UNCHANGED even under --repair" {
  src src/a.ts 'const changedThing = 1;'
  src src/b.ts 'const changedThing = 2;'
  src src/c.ts 'const changedThing = 3;'
  commit_all
  write_index "$(entry 0002F live 'q' 'q' src/old.ts changedThing)"

  run bash "$SCRIPTS_DIR/delivered.sh" verify --repair
  [ "$status" -eq 0 ]
  [[ "$output" == *"0002F=changed"* ]]
  [[ "$output" == *"REPAIRED=0"* ]]
  [ "$(index_lines)" = "1" ]
}

@test "L1.11: repair is idempotent — a second run finds nothing to repair" {
  src src/moved.ts 'const changedThing = 1;'
  commit_all
  write_index "$(entry 0002F live 'q' 'q' src/old.ts changedThing)"
  bash "$SCRIPTS_DIR/delivered.sh" verify --repair >/dev/null
  run bash "$SCRIPTS_DIR/delivered.sh" verify --repair
  [ "$status" -eq 0 ]
  [[ "$output" == *"REPAIRED=0"* ]]
  [ "$(index_lines)" = "2" ]
}

# ─── Status aggregation — the rule the design left open ──────────────────────

@test "aggregation: ALL items gone makes the entry gone" {
  commit_all
  write_index "$(printf '{"v":1,"ts":"2026-09-07T12:00:00Z","id":"0005F","layer":"product","by":"done","status":"live","name":"q","words":"q","commits":["a1b2c3d"],"origin":"o","items":[{"what":"a","at":"src/x.ts","find":"aaaGone"},{"what":"b","at":"src/y.ts","find":"bbbGone"}]}')"
  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0005F=gone"* ]]
}

@test "aggregation: ONE gone among live items makes the entry changed, NEVER gone" {
  # The wrong rule ("any gone -> gone") buries a mostly-alive feature.
  src src/x.ts 'const aaaLive = 1;'
  commit_all
  write_index "$(printf '{"v":1,"ts":"2026-09-07T12:00:00Z","id":"0006F","layer":"product","by":"done","status":"live","name":"q","words":"q","commits":["a1b2c3d"],"origin":"o","items":[{"what":"a","at":"src/x.ts","find":"aaaLive"},{"what":"b","at":"src/y.ts","find":"bbbGone"}]}')"
  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0006F=changed"* ]]
}

@test "aggregation: every item resolving at its own at makes the entry live" {
  src src/x.ts 'const aaaLive = 1;'
  src src/y.ts 'const bbbLive = 2;'
  commit_all
  write_index "$(printf '{"v":1,"ts":"2026-09-07T12:00:00Z","id":"0007F","layer":"product","by":"done","status":"live","name":"q","words":"q","commits":["a1b2c3d"],"origin":"o","items":[{"what":"a","at":"src/x.ts","find":"aaaLive"},{"what":"b","at":"src/y.ts","find":"bbbLive"}]}')"
  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"0007F=live"* ]]
}

# ─── L1.12 — --no-verify opens no source file ────────────────────────────────

@test "L1.12: --no-verify returns the stored status and opens no source file" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index "$(entry 0001F live 'q' 'q' src/live.ts liveThing)"
  # Remove the source. A verifying read would say gone; --no-verify must not look.
  rm -f src/live.ts
  commit_all

  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --no-verify
  [ "$status" -eq 0 ]
  [[ "$output" == *'"status":"live"'* ]]
}

@test "L1.12: the same read WITHOUT --no-verify reports the truth" {
  src src/live.ts 'const liveThing = 1;'
  commit_all
  write_index "$(entry 0001F live 'q' 'q' src/live.ts liveThing)"
  rm -f src/live.ts
  commit_all

  run bash "$SCRIPTS_DIR/delivered.sh" read "q"
  [ "$status" -eq 0 ]
  [[ "$output" == *'"status":"gone"'* ]]
}

@test "L1.12: a verifying read never writes — the file stays byte-identical" {
  src src/moved.ts 'const changedThing = 1;'
  commit_all
  write_index "$(entry 0002F live 'q' 'q' src/old.ts changedThing)"
  local before; before=$(cksum < "$INDEX")
  bash "$SCRIPTS_DIR/delivered.sh" read "q" >/dev/null
  [ "$(cksum < "$INDEX")" = "$before" ]
}

# ─── L1.13 — misuse and a refused write ──────────────────────────────────────

@test "L1.13: a bad mode exits 2" {
  run bash "$SCRIPTS_DIR/delivered.sh" frobnicate
  [ "$status" -eq 2 ]
}

@test "L1.13: no arguments exits 2" {
  run bash "$SCRIPTS_DIR/delivered.sh"
  [ "$status" -eq 2 ]
}

@test "L1.13: read without a query exits 2" {
  run bash "$SCRIPTS_DIR/delivered.sh" read
  [ "$status" -eq 2 ]
}

@test "L1.13: an unknown flag exits 2" {
  commit_all
  run bash "$SCRIPTS_DIR/delivered.sh" read "q" --sort-by-vibes
  [ "$status" -eq 2 ]
}

@test "L1.13: a write the filesystem refuses exits 1, never 0" {
  valid_source; commit_all
  # `docs` is a regular file, so the index directory cannot be created.
  rm -rf docs
  printf 'not a directory\n' > docs
  run_valid_record_write
  [ "$status" -eq 1 ]
  [[ "$output" != *"ENTRY="* ]]
}

@test "L1.13: a missing node prints ERROR=node-missing and exits 2, distinct from REFUSED" {
  commit_all
  local p; p=$(node_free_path)
  PATH="$p" run bash "$SCRIPTS_DIR/delivered.sh" read "q"
  [ "$status" -eq 2 ]
  [[ "$output" == *"ERROR=node-missing"* ]]
  [[ "$output" != *"REFUSED="* ]]
}

# ─── Absence is a no-op, never an error ──────────────────────────────────────

@test "an absent index makes read a no-op with a note, exit 0" {
  commit_all
  run bash "$SCRIPTS_DIR/delivered.sh" read "anything"
  [ "$status" -eq 0 ]
  [ "$(key MATCHED_LIVE)" = "0" ]
  [ "$(key MATCHED_DEAD)" = "0" ]
  [ ! -f "$INDEX" ]
}

@test "an absent index makes verify a no-op, exit 0, and scaffolds nothing" {
  commit_all
  run bash "$SCRIPTS_DIR/delivered.sh" verify
  [ "$status" -eq 0 ]
  [[ "$output" == *"REPAIRED=0"* ]]
  [ ! -f "$INDEX" ]
}

# ─── `node` — the optional join field, at the level the schema defines ───────
#
# Added after a build read design doc -07 (which puts `node` on each ITEM) as
# the authority and reported the script as dropping data. It is not: the format
# reference OWNS the shape, it defines the item as exactly {what, at, find} and
# lists `node` in "The record" table, and serialize() implements that exactly.
#
# The field had ZERO coverage at either level, which is why a correct
# implementation could be read as a defect and would very likely have been
# "fixed" into a spec violation. These levels pin the shape the reference
# defines, so that change fails loudly instead of shipping.

@test "node: an ENTRY-level node round-trips through write" {
  valid_source
  commit_all
  valid_record | sed 's/"items":/"node":"product\/skill\/add-doc-schemas","items":/' \
    > "$TEST_TEMP_DIR/record.json"
  run bash "$SCRIPTS_DIR/delivered.sh" write < "$TEST_TEMP_DIR/record.json"
  [ "$status" -eq 0 ]

  run head -1 "$INDEX"
  [[ "$output" == *'"node":"product/skill/add-doc-schemas"'* ]]
}

@test "node: an ITEM-level node is normalised away — the item is {what, at, find}" {
  valid_source
  commit_all
  # The reference: "Each item is {what, at, find}". A caller may submit more;
  # the written line carries the schema's three and nothing else.
  valid_record | sed 's/"find":"authGoogleHandler"/"find":"authGoogleHandler","node":"product\/skill\/add-doc-schemas"/' \
    > "$TEST_TEMP_DIR/record.json"
  run bash "$SCRIPTS_DIR/delivered.sh" write < "$TEST_TEMP_DIR/record.json"
  [ "$status" -eq 0 ]

  run head -1 "$INDEX"
  # The item object must not carry it. The entry did not declare one either, so
  # the substring must be absent from the whole line.
  [[ "$output" != *'"node"'* ]]
}

@test "node: an entry-level node SURVIVES --repair, so the join is not lost on a move" {
  # The failure this guards: repair re-serialises the entry, so anything
  # serialize() omits dies on the first anchor move. A dropped `node` would
  # break `graph.js history` for that artefact silently and permanently.
  src src/auth/google.ts 'export function authGoogleHandler() { return 1; }'
  commit_all
  valid_record | sed 's/"items":/"node":"product\/skill\/add-doc-schemas","items":/' \
    > "$TEST_TEMP_DIR/record.json"
  bash "$SCRIPTS_DIR/delivered.sh" write < "$TEST_TEMP_DIR/record.json" >/dev/null

  mkdir -p src/auth2
  git mv src/auth/google.ts src/auth2/google.ts >/dev/null 2>&1 || mv src/auth/google.ts src/auth2/google.ts
  commit_all moved

  run bash "$SCRIPTS_DIR/delivered.sh" verify --repair
  [ "$status" -eq 0 ]
  [[ "$output" == *"REPAIRED=1"* ]]

  run tail -1 "$INDEX"
  [[ "$output" == *'"by":"verify"'* ]]
  [[ "$output" == *'"at":"src/auth2/google.ts"'* ]]
  [[ "$output" == *'"node":"product/skill/add-doc-schemas"'* ]]
}

@test "node: a superseded entry is never re-serialised, so superseded_by cannot be lost" {
  # verifyEntry returns no repairs for `superseded`, so --repair must skip it
  # entirely. If it ever re-serialised one, copy.status='changed' would erase
  # both the status and its superseded_by pointer — the one record the index
  # exists to keep.
  src a.md 'marker_beta lives here'
  commit_all
  write_index "$(entry E2 superseded old old a.md marker_beta ',"superseded_by":"E9"')"

  run bash "$SCRIPTS_DIR/delivered.sh" verify --repair
  [ "$status" -eq 0 ]
  [[ "$output" == *"E2=superseded"* ]]
  [[ "$output" == *"REPAIRED=0"* ]]

  [ "$(index_lines)" = "1" ]
  run head -1 "$INDEX"
  [[ "$output" == *'"superseded_by":"E9"'* ]]
  [[ "$output" == *'"status":"superseded"'* ]]
}

# ─── read by node — the join field is part of the haystack ───────────────────
#
# `graph.js history <artefact>` shells out to `read` with the artefact's bare
# name. While `node` sat outside doRead's haystack the verb could only narrow
# what a TEXT search had already found, so it answered correctly exactly while
# an artefact had a single delivery — which is when "was this attempted before?"
# carries the least information. Measured over the whole index: the two nodes
# with more than one delivery each returned one of two.
#
# `items[].at` is deliberately NOT in the haystack. An `at` is a hint that
# --repair rewrites, so matching it would let a query hit a stale pointer.

@test "L4.1: read finds an entry by its node when nothing else in it spells that name" {
  # The shape that made `durable-delivery-history` invisible: the node names the
  # artefact and the id, name, words and item text never do.
  src a.md 'marker_gamma lives here'
  commit_all
  write_index "$(entry E1 live 'a delivery' 'unrelated words only' a.md marker_gamma ',"node":"internal/command/add-framework--done"')"

  run bash "$SCRIPTS_DIR/delivered.sh" read "add-framework--done"
  [ "$status" -eq 0 ]
  [[ "$output" == *"MATCHED_LIVE=1"* ]]
  [[ "$output" == *'"id":"E1"'* ]]
}

@test "L4.2: a query in no entry's text and no entry's node still returns nothing" {
  # Guards the haystack change against over-matching: adding a field must not
  # turn every query into a hit.
  src a.md 'marker_gamma lives here'
  commit_all
  write_index "$(entry E1 live 'a delivery' 'unrelated words only' a.md marker_gamma ',"node":"internal/command/add-framework--done"')"

  run bash "$SCRIPTS_DIR/delivered.sh" read "add-framework--roadmap"
  [ "$status" -eq 0 ]
  [[ "$output" == *"MATCHED_LIVE=0"* ]]
  [[ "$output" != *'"id":"E1"'* ]]
}

@test "L4.3: an entry with no node at all is still readable by its text" {
  # The field is optional — top-level scripts, CLAUDE.md and .gitignore produce
  # no graph node — so the haystack must tolerate its absence.
  src a.md 'marker_gamma lives here'
  commit_all
  write_index "$(entry E1 live 'a delivery' 'unrelated words only' a.md marker_gamma)"

  run bash "$SCRIPTS_DIR/delivered.sh" read "unrelated"
  [ "$status" -eq 0 ]
  [[ "$output" == *'"id":"E1"'* ]]
}

# ─── L1 — `touched`, the path query ──────────────────────────────────────────
#
# The delivery's commit is DERIVED, never stored: the close-out commits the
# index line on the branch and the merge squashes that branch, so the commit
# that introduced an entry's line is the commit that delivered it. These
# fixtures build that shape with real commits rather than asserting it.

# seed_delivery <id> <file> <find> — the SQUASH shape, which is the one the
# derivation depends on. The close-out commits the index line on the branch and
# the merge squashes the whole branch, so on the default branch ONE commit
# carries both the delivery's code and its index line. A fixture that commits
# them separately builds the docs/-only case instead, which L1.4 covers on
# purpose.
seed_delivery() {
  local id=$1 file=$2 find=$3
  src "$file" "const ${find} = 1;"
  mkdir -p docs
  entry "$id" live "delivery $id" "words $id" "$file" "$find" >> "$INDEX"
  printf '\n' >> "$INDEX"
  commit_all "squash for $id: code and index line together"
}

@test "L1.1: touched returns the delivery whose derived commit changed the path" {
  seed_delivery D1 src/one.ts markerOne
  run bash "$SCRIPTS_DIR/delivered.sh" touched src/one.ts
  [ "$status" -eq 0 ]
  [[ "$output" == *'"id":"D1"'* ]]
  [[ "$output" == *'"answer":"complete"'* ]]
}

@test "L1.2: an entry whose at names the path but whose commit does not comes back curated" {
  # The source file is committed in the SAME commit as the index line, so the
  # derived commit does touch it — to get a curated-only hit the anchor has to
  # point at a file that commit never changed.
  seed_delivery D2 src/two.ts markerTwo
  src src/other.ts 'const markerOther = 1;'
  commit_all "a later file the D2 commit never saw"
  mkdir -p docs
  entry D3 live 'delivery D3' 'words D3' src/other.ts markerOther >> "$INDEX"
  printf '\n' >> "$INDEX"
  git add -A >/dev/null 2>&1; git commit -q -m "index line for D3, source already committed" >/dev/null 2>&1 || true

  run bash "$SCRIPTS_DIR/delivered.sh" touched src/other.ts
  [ "$status" -eq 0 ]
  [[ "$output" == *'"id":"D3"'* ]]
  [[ "$output" == *'"answer":"curated"'* ]]
}

@test "L1.3: the derivation finds the line's FIRST commit, not a later correction" {
  seed_delivery D4 src/four.ts markerFour
  local first
  first=$(git log --format=%h -1)
  # A correction line for the same id, in a later commit.
  entry D4 live 'delivery D4 corrected' 'words D4' src/four.ts markerFour >> "$INDEX"
  printf '\n' >> "$INDEX"
  git add -A >/dev/null 2>&1; git commit -q -m "correction line for D4" >/dev/null 2>&1 || true

  run bash "$SCRIPTS_DIR/delivered.sh" touched src/four.ts
  [ "$status" -eq 0 ]
  [[ "$output" == *"$first"* ]]
}

@test "L1.4: an entry whose derived commit touches only docs/ answers curated" {
  src src/five.ts 'const markerFive = 1;'
  commit_all "source, committed alone"
  mkdir -p docs
  entry D5 live 'delivery D5' 'words D5' src/five.ts markerFive >> "$INDEX"
  printf '\n' >> "$INDEX"
  git add docs >/dev/null 2>&1
  git commit -q -m "chore(delivery-index): record D5 after the fact" >/dev/null 2>&1 || true

  run bash "$SCRIPTS_DIR/delivered.sh" touched src/five.ts
  [ "$status" -eq 0 ]
  [[ "$output" == *'"answer":"curated"'* ]]
  [ "$(key CURATED_ONLY)" = "1" ]
}

@test "L1.5: CURATED_ONLY counts every entry that could not answer from its commit" {
  src src/six.ts 'const markerSix = 1;'
  src src/seven.ts 'const markerSeven = 1;'
  commit_all "both sources"
  mkdir -p docs
  entry D6 live 'delivery D6' 'words D6' src/six.ts markerSix >> "$INDEX"
  printf '\n' >> "$INDEX"
  entry D7 live 'delivery D7' 'words D7' src/seven.ts markerSeven >> "$INDEX"
  printf '\n' >> "$INDEX"
  git add docs >/dev/null 2>&1
  git commit -q -m "chore(delivery-index): record both after the fact" >/dev/null 2>&1 || true

  run bash "$SCRIPTS_DIR/delivered.sh" touched src/six.ts src/seven.ts
  [ "$status" -eq 0 ]
  [ "$(key CURATED_ONLY)" = "2" ]
}

@test "L1.6: a path no delivery touched returns both blocks empty, exit 0" {
  seed_delivery D8 src/eight.ts markerEight
  run bash "$SCRIPTS_DIR/delivered.sh" touched src/nowhere.ts
  [ "$status" -eq 0 ]
  [ "$(key TOUCHED_COMPLETE)" = "0" ]
  [ "$(key TOUCHED_CURATED)" = "0" ]
  [ "$(json_lines | wc -l | tr -d ' ')" = "0" ]
  # DISTINGUISHABLE from an absent index, and from the OUTPUT rather than from
  # the filesystem: a caller reading three zeros cannot otherwise tell "nothing
  # matched" from "there is nothing to match against".
  [ "$(key INDEX_PRESENT)" = "1" ]
}

@test "L1.7: an absent index makes touched a no-op, and says so in the output" {
  commit_all "no index at all"
  run bash "$SCRIPTS_DIR/delivered.sh" touched src/anything.ts
  [ "$status" -eq 0 ]
  [ "$(key TOUCHED_COMPLETE)" = "0" ]
  [ "$(key TOUCHED_CURATED)" = "0" ]
  [ "$(key INDEX_PRESENT)" = "0" ]
  [ ! -f "$INDEX" ]
}

@test "L1.7b: a history git cannot walk degrades to curated, never to an error" {
  # The shallow-clone case the plan names. Simulated by an index whose entry
  # predates any commit that carries it: no commit introduced that id, so the
  # derivation finds no owning sha and the anchors are all that can answer.
  src src/nine.ts 'const markerNine = 1;'
  commit_all "source only, the index line never committed"
  mkdir -p docs
  entry D9 live 'delivery D9' 'words D9' src/nine.ts markerNine >> "$INDEX"
  printf '\n' >> "$INDEX"

  run bash "$SCRIPTS_DIR/delivered.sh" touched src/nine.ts
  [ "$status" -eq 0 ]
  [ "$(key TOUCHED_CURATED)" = "1" ]
  [ "$(key CURATED_ONLY)" = "1" ]
  [[ "$output" == *'"answer":"curated"'* ]]
}

@test "L1.7c: a delivery landed by a MERGE commit still answers complete, with the merge sha" {
  # The PR route of both close-outs merges with --merge. The code and the index
  # line land in SEPARATE branch commits — the second one touches only docs/ —
  # and the merge commit is what brings both to the default branch. Reading the
  # branch commit that introduced the line would call it a docs/-only recording
  # and degrade every such delivery to curated. The first-parent walk reads the
  # merge commit instead, whose diff against its first parent is the delivery.
  src src/base.ts 'const markerBase = 1;'
  commit_all "base"
  local trunk
  trunk=$(git rev-parse --abbrev-ref HEAD)
  git checkout -q -b feat
  src src/ten.ts 'const markerTen = 1;'
  commit_all "F1: code"
  mkdir -p docs
  entry D10 live 'delivery D10' 'words D10' src/ten.ts markerTen >> "$INDEX"
  printf '\n' >> "$INDEX"
  git add docs >/dev/null 2>&1
  git commit -q -m "docs: index entry for D10" >/dev/null 2>&1
  git checkout -q "$trunk"
  git merge -q --no-ff feat -m "Merge pull request: D10" >/dev/null 2>&1
  local merge
  merge=$(git log --format=%h -1)

  run bash "$SCRIPTS_DIR/delivered.sh" touched src/ten.ts
  [ "$status" -eq 0 ]
  [[ "$output" == *'"answer":"complete"'* ]]
  [[ "$output" == *"\"commit\":\"$merge\""* ]]
  [ "$(key CURATED_ONLY)" = "0" ]
}

@test "L1.8: touched with no path exits 2" {
  # GUARD, and green before the mode existed: an unknown mode already falls
  # through to usage. It stays so the mode cannot be added with a path list that
  # silently defaults to everything.
  run bash "$SCRIPTS_DIR/delivered.sh" touched
  [ "$status" -eq 2 ]
}
