/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as ListRouteImport } from './routes/list'
import { Route as BoardTicketIdRouteImport } from './routes/board.$ticketId'
import { Route as ListTicketIdRouteImport } from './routes/list.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardTicketIdRoute = BoardTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => BoardRoute,
} as any)
const ListTicketIdRoute = ListTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => ListRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/list': typeof ListRouteWithChildren
  '/board/$ticketId': typeof BoardTicketIdRoute
  '/list/$ticketId': typeof ListTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/list': typeof ListRouteWithChildren
  '/board/$ticketId': typeof BoardTicketIdRoute
  '/list/$ticketId': typeof ListTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/list': typeof ListRouteWithChildren
  '/board/$ticketId': typeof BoardTicketIdRoute
  '/list/$ticketId': typeof ListTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/board' | '/list' | '/board/$ticketId' | '/list/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/board' | '/list' | '/board/$ticketId' | '/list/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/list'
    | '/board/$ticketId'
    | '/list/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRouteWithChildren
  ListRoute: typeof ListRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$ticketId': {
      id: '/board/$ticketId'
      path: '/$ticketId'
      fullPath: '/board/$ticketId'
      preLoaderRoute: typeof BoardTicketIdRouteImport
      parentRoute: typeof BoardRoute
    }
    '/list/$ticketId': {
      id: '/list/$ticketId'
      path: '/$ticketId'
      fullPath: '/list/$ticketId'
      preLoaderRoute: typeof ListTicketIdRouteImport
      parentRoute: typeof ListRoute
    }
  }
}

interface BoardRouteChildren {
  BoardTicketIdRoute: typeof BoardTicketIdRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardTicketIdRoute: BoardTicketIdRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

interface ListRouteChildren {
  ListTicketIdRoute: typeof ListTicketIdRoute
}

const ListRouteChildren: ListRouteChildren = {
  ListTicketIdRoute: ListTicketIdRoute,
}

const ListRouteWithChildren = ListRoute._addFileChildren(ListRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRouteWithChildren,
  ListRoute: ListRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
